[package]
name = "cobalt"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glad-gl = { path = "./external/glad" }
glfw = "0.52.0"
hecs = "0.10.3"
log = "0.4.19"
nalgebra-glm = "0.18.0"
stb_image = "0.2.5"

[dev-dependencies]
chrono = "0.4.26"
criterion = "0.5.1"
log4rs = "1.2.0"
serde_yaml = "0.9.25"

